import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuBar from "@/components/MenuBar";
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import NextAuthProvider from "@/providers/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "vaccine-book-app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nextAuthSession = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider session={nextAuthSession}>
          <MenuBar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
