import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MenuBar from "@/components/MenuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assignment 3 and 4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuBar/>
        {children}
        </body>
    </html>
  );
}
